version: 2.1
orbs:
  hmpps: ministryofjustice/hmpps@9
parameters:
  releases-slack-channel:
    type: string
    default: legacy-replacement-releases
  jdk-tag:
    type: string
    default: "21.0"
jobs:
  validate:
    executor:
      name: hmpps/java_localstack_postgres_with_db_name
      jdk_tag: << pipeline.parameters.jdk-tag >>
      localstack_tag: "3"
      services: "sqs,sns"
      postgres_tag: "16"
      postgres_username: "admin"
      postgres_password: "admin_password"
      postgres_db: "court_register_db"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
workflows:
  version: 2
